version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run: 
          name: Install Testing Env
          command: mkdir test-results && pip install tox
      - run:
          name: Run Test Suite
          command: tox
      - store_artifacts:
          path: test-results/pyextensions/
      - store_test_results:
          path: test-results/pyextensions/
  deploy:
    docker:
      - image: python:3
    steps:
        - checkout
        - run:
            name: install python dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make dev
        - run:
            name: verify git tag vs. version
            command: |
              python3 -m venv venv
              . venv/bin/activate
              python setup.py verify
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = levlaz" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: create packages
            command: |
              make package
        - run:
            name: upload to test-pypi
            command: |
              . venv/bin/activate
              twine upload --repository-url https://test.pypi.org/legacy/ dist/*